### ISSUE TITLE
fail to get access to the data from the set up Gluu server 

### ISSUE THREAD

**Issue by KypMon** [GluuFederation/SCIM-Node#3]
I am trying to use the SCIM-Node library to get access the gluu server that is working. With the example code shown in the README documentation. 

like these

```
const config = {
    keyAlg: 'RSA', // Algorithm type.
    domain: GLUU_SERVER_URL, // Gluu server URL.
    privateKey: './path/private_key', // Value can be buffer or path of private key.
    clientId: 'OUR CLIENT ID', // UMA client id.
    keyId: 'OUR KEY ID', // oxAuth JWKS key id.
  };

const scim = require('scim-node')(config);

scim.scim.getUsersCount((err, data) => {
    console.log(err);
});

```

and we got error like this
```
{ StatusCodeError: 404 - "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p>The requested URL /.well-known/uma-configuration was not found on this server.</p>\n<hr>\n<address>Apache/2.4.18 (Ubuntu) Server at gluu.COMPANY_NAME.com Port 443</address>\n</body></html>\n"
    at new StatusCodeError (./node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (./node_modules/request-promise-core/lib/plumbing.js:104:33)
```
Aopreciate for help of any kinds. Thanks

**Comment by nynymike** [comment]
```
 /.well-known/uma-configuration
```
Shouldn't that be *uma2-configuration*

**Comment by ldeveloperl1985** [comment]
@KanesYang Use **scim2** as given below. here is README doc. https://github.com/GluuFederation/SCIM-Node#1-getuserscount

```
scim.scim2.getUsersCount((err, data) => {
    console.log(err);
});
```

**Comment by KanesYang** [comment]
@nynymike  @ldeveloperl1985  Thanks for pointing out, but actually I try with scim2 first, like this code
```
    scim.scim2.getUsersCount().then((data) => {
        console.log(data);
    }).catch((err) => {
        console.error(err);
    });
```
, and got an error like 
```
Unhandled rejection ReferenceError: data is not defined
    at /Users/admin/backend/node_modules/scim-node/lib/scim2.js:92:20
From previous event:
    at /Users/admin/backend/node_modules/scim-node/lib/scim2.js:86:15
    at getTicketAndConfig (/Users/admin/backend/node_modules/scim-node/lib/scim2.js:76:12)
    at /Users/admin/backend/node_modules/scim-node/lib/scim2.js:189:18
    at bound (domain.js:396:14)
    at runBound (domain.js:409:12)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
    at process.topLevelDomainCallback (domain.js:121:23)
```

There is actually a problem for me to connect to gluu that, I am trying to figure out the config params of an existing gluu server. But actually I am quite new to Gluu server. So I think I may fill in the wrong params. Would you mind to tell me where should I find these params or give me something to read? Much appreciated.

**Comment by ldeveloperl1985** [comment]
@KanesYang try with latest version 
```
npm install scim-node@latest --save

or

npm install scim-node@2.1.1 --save
```

You can use our java client also [SCIM-Client](https://github.com/GluuFederation/SCIM-Client). 
For params, refer this doc https://www.gluu.org/docs/ce/user-management/scim2/#testing-with-the-scim-client-uma

**Comment by KanesYang** [comment]
@ldeveloperl1985  Thanks for replying. It helps me to better understand the way it works. after several attempts, the code still doesn't work expectedly. And unfortunately, I still confused about the sources of some attributes.

- for the key algorithm type, I found it in the Configuration > JSON configuration > oxAuth Configuration, in _defaultSignatureAlgorithm_, is that the one for this attribute?
- For the private key, it should be looks like this `'./output/scim-rp.jks'` (my previous value) or this  `'/install/community-edition-setup/output/scim-rp.jks'` (which I found from the documemtation)

I know it is quite annoying for your guys to answer dummy questions like these, but I have been stucked on this for several days. Would be much appreciated for your help.

**Comment by ldeveloperl1985** [comment]
1. For  key algorithm, you are right. Take this `defaultSignatureAlgorithm`
2. For private key, you need to export private key from jks file. Use this solution https://security.stackexchange.com/a/66865 or try any other solution for export private key.

**Comment by KanesYang** [comment]
@ldeveloperl1985  Thanks, it works.
